# Generated by Django 4.2.2 on 2023-06-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamento',
            new_name='Equipamentos',
        ),
    ]
