# Generated by Django 4.2.2 on 2023-06-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_equipment_status_delete_equipamentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Host',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
