# Generated by Django 4.2.2 on 2023-07-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0004_rename_equipment_host_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=15)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
