# Generated by Django 4.2.2 on 2023-07-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0005_equipamentos_delete_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamentos',
            old_name='is_online',
            new_name='online',
        ),
    ]
